language: python
dist: bionic
cache: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

service:
  - redis-server

install:
  - pip install tox-travis

script:
  - tox


deploy:
  provider: pypi
  username: atuchak
  edge: true
  skip_existing: true
  on:
    tags: true